// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorAppWebAssembly.Shared.Models
{
    public partial class customer
    {
        public ulong id { get; set; }
        public string name { get; set; }
        public string bar_id { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string note { get; set; }
        public string user { get; set; }
        public string fak_adress { get; set; }
        public string fak_psc { get; set; }
        public string fak_mesto { get; set; }
        public string ico { get; set; }
        public string dic { get; set; }
        public string osoba { get; set; }
        public string ucet { get; set; }
        public string banka { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public int typ { get; set; }
        public string dod_psc { get; set; }
        public string dod_mesto { get; set; }
        public string externi_id { get; set; }
        public int? barvaPlanu { get; set; }
        public string dod_osoba { get; set; }
        public string dod_stat { get; set; }
        public string fak_firma { get; set; }
        public string fak_osoba { get; set; }
        public string dod_firma { get; set; }
        public string fak_oddeleni { get; set; }
        public string dod_oddeleni { get; set; }
        public string fak_phone { get; set; }
        public string fak_email { get; set; }
        public string fak_stat { get; set; }
        public int email_odesilat { get; set; }
        public int splatnost_dni { get; set; }
        public string doprava { get; set; }
        public string platba { get; set; }
        public string dorucenifaktury { get; set; }
        public string forma { get; set; }
        public int gdpr_zbyva { get; set; }
        public int gdpr_anonymizovano { get; set; }
        public int prima_dodaci_adresa { get; set; }
        public string icdph { get; set; }
        public DateTime ts_lastChange { get; set; }
        public DateTime ts_created { get; set; }
        public int oblast { get; set; }
    }
}