// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorAppWebAssembly.Shared.Models
{
    public partial class readdata
    {
        public ulong id { get; set; }
        public DateTime start { get; set; }
        public DateTime finish { get; set; }
        public string order_id { get; set; }
        public ulong operation_id { get; set; }
        public int worker_id { get; set; }
        public int repair_type { get; set; }
        public string note { get; set; }
        public string user { get; set; }
        public int calculated { get; set; }
        public int order_group_id { get; set; }
        public int calculated_machine { get; set; }
        public decimal mnoz { get; set; }
        public decimal ukonova_mzda { get; set; }
        public int added_price { get; set; }
        public decimal naklady { get; set; }
        public ulong serial_id { get; set; }
        public int exportovano { get; set; }
        public decimal ukon_mzda { get; set; }
        public int typ_ukon_mzdy { get; set; }
        public decimal zmetku { get; set; }
        public int worker_id2 { get; set; }
        public int volitelna1 { get; set; }
        public int kusy_zapocteno { get; set; }
        public int calculated_orderwork { get; set; }
        public int calculated_kalendar { get; set; }
        public int photo_count { get; set; }
        public int priorita { get; set; }
        public int dodaci_list_polozka_id { get; set; }
        public decimal volitelna2 { get; set; }
        public string serial_id_str { get; set; }
        public int? hnizdo { get; set; }
        public int? poradi_operace { get; set; }
        public int? orderwork_id { get; set; }
        public int zamceno { get; set; }
        public DateTime zamceno_cas { get; set; }
        public int zamceno_id_user { get; set; }
        public string sarze { get; set; }
        public decimal naklady_vstup { get; set; }
        public int locked { get; set; }
        public decimal cena_worker { get; set; }
        public decimal cena_worker2 { get; set; }
        public decimal cena_operation { get; set; }
        public decimal cena_cnc { get; set; }
        public decimal cena_stroj { get; set; }
        public int? faktura_id { get; set; }
        public string faktura_doklad { get; set; }
        public decimal cena_MJ { get; set; }
        public int typ_vypoctu { get; set; }
        public int prepocitano { get; set; }
        public decimal naklady_worker { get; set; }
        public decimal naklady_order { get; set; }
        public decimal naklady_operation { get; set; }
        public int? um_uznano { get; set; }
        public int? um_fond_odpis { get; set; }
        public int? um_fond_zbyva { get; set; }
        public DateTime? um_uznano_datum { get; set; }
        public string um_uznano_user { get; set; }
        public string externi_id { get; set; }
        public int ceny_added { get; set; }
        public string terminal_ip { get; set; }
        public DateTime ts_lastChange { get; set; }
        public DateTime ts_created { get; set; }
    }
}