// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BlazorCRUD1
{
    public partial class TprContext : DbContext
    {
        public TprContext()
        {
        }

        public TprContext(DbContextOptions<TprContext> options)
            : base(options)
        {
        }

        public virtual DbSet<c_order> c_order { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<operation> operation { get; set; }
        public virtual DbSet<order_stav> order_stav { get; set; }
        public virtual DbSet<readdata> readdata { get; set; }
        public virtual DbSet<worker> worker { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<c_order>(entity =>
            {
                entity.HasIndex(e => e.active)
                    .HasName("active");

                entity.HasIndex(e => e.bar_id)
                    .HasName("bar_id");

                entity.HasIndex(e => e.ciselna_volitelna1)
                    .HasName("ciselna_volitelna1");

                entity.HasIndex(e => e.ciselna_volitelna2)
                    .HasName("ciselna_volitelna2");

                entity.HasIndex(e => e.ciselna_volitelna3)
                    .HasName("ciselna_volitelna3");

                entity.HasIndex(e => e.ciselna_volitelna4)
                    .HasName("ciselna_volitelna4");

                entity.HasIndex(e => e.ciselna_volitelna5)
                    .HasName("ciselna_volitelna5");

                entity.HasIndex(e => e.code)
                    .HasName("code");

                entity.HasIndex(e => e.created_mat_id)
                    .HasName("created_mat_id");

                entity.HasIndex(e => e.customer_id)
                    .HasName("customer_id");

                entity.HasIndex(e => e.datumExpedice)
                    .HasName("datumExpedice");

                entity.HasIndex(e => e.dispTree)
                    .HasName("dispTree");

                entity.HasIndex(e => e.drawing)
                    .HasName("drawing");

                entity.HasIndex(e => e.externi_id)
                    .HasName("externi_id");

                entity.HasIndex(e => e.finish)
                    .HasName("finish");

                entity.HasIndex(e => e.finishVyroba)
                    .HasName("finishVyroba");

                entity.HasIndex(e => e.force_prepocet)
                    .HasName("force_prepocet");

                entity.HasIndex(e => e.gdpr_zbyva)
                    .HasName("gdpr_zbyva");

                entity.HasIndex(e => e.masterOrderId)
                    .HasName("masterOrderId");

                entity.HasIndex(e => e.name)
                    .HasName("name");

                entity.HasIndex(e => e.order_cena_jednotka)
                    .HasName("order_cena_jednotka");

                entity.HasIndex(e => e.parent_id)
                    .HasName("parent_id");

                entity.HasIndex(e => e.rozmer1)
                    .HasName("rozmer1");

                entity.HasIndex(e => e.rozmer2)
                    .HasName("rozmer2");

                entity.HasIndex(e => e.rozmer3)
                    .HasName("rozmer3");

                entity.HasIndex(e => e.start)
                    .HasName("start");

                entity.HasIndex(e => e.startVyroba)
                    .HasName("startVyroba");

                entity.HasIndex(e => e.ts_created)
                    .HasName("ts_created");

                entity.HasIndex(e => e.ts_lastChange)
                    .HasName("ts_lastChange");

                entity.HasIndex(e => e.typ)
                    .HasName("typ");

                entity.HasIndex(e => e.uroven)
                    .HasName("uroven");

                entity.HasIndex(e => e.volitelna10)
                    .HasName("volitelna10");

                entity.HasIndex(e => e.volitelna15)
                    .HasName("volitelna15");

                entity.HasIndex(e => e.volitelna16)
                    .HasName("volitelna16");

                entity.HasIndex(e => e.volitelna3)
                    .HasName("volitelna3");

                entity.HasIndex(e => e.zpusob_dopravy_id)
                    .HasName("zpusob_dopravy_id");

                entity.HasIndex(e => new { e.bar_id, e.dispTree })
                    .HasName("bar_id,dispTree");

                entity.Property(e => e.active)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.baliku1)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.baliku2)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.baliku3)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.bar_id)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.ciselna_volitelna1)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.ciselna_volitelna2)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.ciselna_volitelna3)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.ciselna_volitelna4)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.ciselna_volitelna5)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.ciselna_volitelna6)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.cislo_objednavky)
                    .IsRequired()
                    .HasColumnType("varchar(25)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.code)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.created)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");

                entity.Property(e => e.created_mat_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.customer_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.customer_id_adresa)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.customer_name)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.datumExpedice)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'0000-00-00'");

                entity.Property(e => e.datumcaszmeny)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.datumova_volitelna1)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.datumova_volitelna2)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.datumova_volitelna3)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.datumova_volitelna4)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.dispTree)
                    .IsRequired()
                    .HasColumnType("varchar(72)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.drawing)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.druha_mena_zkratka)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.email_upozornovat)
                    .HasColumnType("int(4)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.expandovano)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.externi_faktura).HasColumnType("varchar(100)");

                entity.Property(e => e.externi_id)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.finish)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'0000-00-00'");

                entity.Property(e => e.finishVyroba)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.force_prepocet)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.gdpr_anonymizovano)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.gdpr_zbyva)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.has_docs)
                    .HasColumnType("int(3)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.id_ciselna_rada)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.id_pohoda)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.int_bar_id).HasDefaultValueSql("'9999999999'");

                entity.Property(e => e.is_sablona)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.koeficient_on)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'1.00'");

                entity.Property(e => e.kusu)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.last_op).HasDefaultValueSql("'0'");

                entity.Property(e => e.masterOrderId)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.montaz_date)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'0000-00-00'");

                entity.Property(e => e.montaz_time)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.note).HasColumnType("text");

                entity.Property(e => e.note2).HasColumnType("text");

                entity.Property(e => e.note_nabidka).HasColumnType("text");

                entity.Property(e => e.odmeny_predpoklad)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.odmeny_vyuctovano)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.oken_unit)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.operation_group_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.order_cena_jednotka)
                    .HasColumnType("decimal(15,4)")
                    .HasDefaultValueSql("'0.0000'");

                entity.Property(e => e.parent_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.plan_kalendar)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.pocetKlt)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.prefix_ciselna_rada)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.prevedeno)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.price_ukony)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.priorita)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.real_mzda)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.real_price)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.real_price2)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.real_time)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.rozmer1)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.rozmer2)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.rozmer3)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.sklad_group_id)
                    .HasColumnType("int(16)")
                    .HasDefaultValueSql("'-1'");

                entity.Property(e => e.start)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'0000-00-00'");

                entity.Property(e => e.startVyroba)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.techpostup_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.ts_created)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                entity.Property(e => e.ts_lastChange)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'")
                    .ValueGeneratedOnAddOrUpdate();

                entity.Property(e => e.typ)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.typ_vypoctu_ceny)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.ukon10_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon10_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon11_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon11_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon12_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon12_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon13_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon13_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon14_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon14_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon15_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon15_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon1_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon1_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon2_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon2_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon3_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon3_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon4_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon4_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon5_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon5_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon6_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon6_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon7_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon7_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon8_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon8_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon9_planks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.ukon9_vyrobenoks)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.unirec).HasColumnType("varchar(256)");

                entity.Property(e => e.unit)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'1'");

                entity.Property(e => e.uroven)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.user)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");

                entity.Property(e => e.user_price)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.user_price_mat)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.user_price_sub)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.user_price_work)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.user_time)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.user_time_ks_second)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.user_time_order)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.viceprace)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna1)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna10)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna11).HasColumnType("varchar(200)");

                entity.Property(e => e.volitelna12).HasColumnType("varchar(200)");

                entity.Property(e => e.volitelna13)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna14)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.volitelna15)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.volitelna16)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.volitelna2)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna3)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna4)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna5)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna6)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna7)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna8)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna9)
                    .IsRequired()
                    .HasColumnType("varchar(200)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.vykres_ze_souboru).HasColumnType("int(2)");

                entity.Property(e => e.vypocteno_vyrobeno)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.zpusob_dopravy_id).HasDefaultValueSql("'0'");
            });

            modelBuilder.Entity<customer>(entity =>
            {
                entity.HasIndex(e => e.bar_id)
                    .HasName("bar_id");

                entity.HasIndex(e => e.doprava)
                    .HasName("doprava");

                entity.HasIndex(e => e.email_odesilat)
                    .HasName("email_odesilat");

                entity.HasIndex(e => e.externi_id)
                    .HasName("externi_id");

                entity.HasIndex(e => e.gdpr_zbyva)
                    .HasName("gdpr_zbyva");

                entity.HasIndex(e => e.ico)
                    .HasName("ico");

                entity.HasIndex(e => e.name)
                    .HasName("name");

                entity.HasIndex(e => e.platba)
                    .HasName("platba");

                entity.HasIndex(e => e.ts_created)
                    .HasName("ts_created");

                entity.HasIndex(e => e.ts_lastChange)
                    .HasName("ts_lastChange");

                entity.HasIndex(e => e.typ)
                    .HasName("typ");

                entity.Property(e => e.adress)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.banka)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.bar_id)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.barvaPlanu).HasColumnType("int(11)");

                entity.Property(e => e.dic)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("'CZ'");

                entity.Property(e => e.dod_firma)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.dod_mesto)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.dod_oddeleni)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.dod_osoba)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.dod_psc)
                    .IsRequired()
                    .HasColumnType("varchar(10)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.dod_stat)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.doprava)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.dorucenifaktury)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.email)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.email_odesilat)
                    .HasColumnType("int(4)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.externi_id)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_adress)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_email)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_firma)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_mesto)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_oddeleni)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_osoba)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_phone)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_psc)
                    .IsRequired()
                    .HasColumnType("varchar(10)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fak_stat)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.fax)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.forma)
                    .IsRequired()
                    .HasColumnType("varchar(10)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.gdpr_anonymizovano)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.gdpr_zbyva)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.icdph)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.ico)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.mobile)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.note).HasColumnType("text");

                entity.Property(e => e.oblast)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.osoba)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.phone)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.platba)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.prima_dodaci_adresa)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.splatnost_dni)
                    .HasColumnType("int(4)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.ts_created)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                entity.Property(e => e.ts_lastChange)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'")
                    .ValueGeneratedOnAddOrUpdate();

                entity.Property(e => e.typ)
                    .HasColumnType("int(3)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.ucet)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.user)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");

                entity.Property(e => e.web)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");
            });

            modelBuilder.Entity<operation>(entity =>
            {
                entity.HasIndex(e => e.bar_id)
                    .HasName("bar_id");

                entity.HasIndex(e => e.externi_id)
                    .HasName("externi_id");

                entity.HasIndex(e => e.group_id)
                    .HasName("group_id");

                entity.HasIndex(e => e.id_employee)
                    .HasName("id_employee");

                entity.HasIndex(e => e.machine_name)
                    .HasName("machine_name");

                entity.HasIndex(e => e.name)
                    .HasName("name");

                entity.HasIndex(e => e.operace_predchazejici_fix)
                    .HasName("operace_predchazejici_fix");

                entity.HasIndex(e => e.operace_predchazejici_id)
                    .HasName("operace_predchazejici_id");

                entity.HasIndex(e => e.orderstav_id)
                    .HasName("orderstav_id");

                entity.HasIndex(e => e.priprava)
                    .HasName("priprava");

                entity.HasIndex(e => e.pripravaCas)
                    .HasName("pripravaCas");

                entity.HasIndex(e => e.pripravaInterval)
                    .HasName("pripravaInterval");

                entity.HasIndex(e => e.ts_created)
                    .HasName("ts_created");

                entity.HasIndex(e => e.ts_lastChange)
                    .HasName("ts_lastChange");

                entity.HasIndex(e => e.ukolova_mzda)
                    .HasName("ukolova_mzda");

                entity.HasIndex(e => e.userCode)
                    .HasName("userCode");

                entity.Property(e => e.auto_writte)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.bar_id)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cena_faktura)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.cena_mj_odmeny)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.cena_mj_operace)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.cena_mzdove_polozky)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.cena_rezie)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.cnc_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'1'");

                entity.Property(e => e.externi_id)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.group_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.group_name).HasColumnType("varchar(50)");

                entity.Property(e => e.id_employee)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.is_cnc)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.is_dochazka)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.koeficient_mzdy)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.machine_name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.maxmin_za_den)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.note).HasColumnType("text");

                entity.Property(e => e.open_door)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.operace_predchazejici_cas).HasColumnType("int(12)");

                entity.Property(e => e.operace_predchazejici_fix).HasColumnType("int(2)");

                entity.Property(e => e.operace_predchazejici_id).HasColumnType("int(12)");

                entity.Property(e => e.orderstav_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'-1'");

                entity.Property(e => e.planovano_min)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.priprava)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.pripravaCas)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.pripravaInterval)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.resource_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.sklad_skupina_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.take_photo)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.ts_created)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                entity.Property(e => e.ts_lastChange)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'")
                    .ValueGeneratedOnAddOrUpdate();

                entity.Property(e => e.ukolova_mzda)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.unit)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.unit_price)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.unitcount)
                    .HasColumnType("decimal(15,5)")
                    .HasDefaultValueSql("'0.00000'");

                entity.Property(e => e.user)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");

                entity.Property(e => e.userCode)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");
            });

            modelBuilder.Entity<order_stav>(entity =>
            {
                entity.HasIndex(e => e.FinalStatus)
                    .HasName("FinalStatus");

                entity.HasIndex(e => e.blokace_mat)
                    .HasName("blokace_mat");

                entity.HasIndex(e => e.change_operation_id)
                    .HasName("change_operation_id");

                entity.HasIndex(e => e.group_name)
                    .HasName("group_name");

                entity.HasIndex(e => e.name)
                    .HasName("name");

                entity.HasIndex(e => e.pocitat_plan)
                    .HasName("pocitat_plan");

                entity.HasIndex(e => e.poradi)
                    .HasName("poradi");

                entity.HasIndex(e => e.prepocitavat)
                    .HasName("prepocitavat");

                entity.HasIndex(e => e.stav_vyroba)
                    .HasName("stav_vyroba");

                entity.Property(e => e.id).HasColumnType("int(11)");

                entity.Property(e => e.FinalStatus)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.barevne_oznaceni)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.barva)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.blokace_mat)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'1'");

                entity.Property(e => e.change_operation_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.cislo)
                    .IsRequired()
                    .HasColumnType("varchar(25)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.group_name)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.in_print)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.pocitat_plan)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'1'");

                entity.Property(e => e.poradi)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.prepocitavat)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'1'");

                entity.Property(e => e.stav_vyroba)
                    .HasColumnType("int(10)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.user)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");
            });

            modelBuilder.Entity<readdata>(entity =>
            {
                entity.HasIndex(e => e.calculated)
                    .HasName("calculated");

                entity.HasIndex(e => e.calculated_machine)
                    .HasName("calculated_machine");

                entity.HasIndex(e => e.calculated_orderwork)
                    .HasName("calculated_orderwork");

                entity.HasIndex(e => e.ceny_added)
                    .HasName("ceny_added");

                entity.HasIndex(e => e.dodaci_list_polozka_id)
                    .HasName("dodaci_list_polozka_id");

                entity.HasIndex(e => e.exportovano)
                    .HasName("exportovano");

                entity.HasIndex(e => e.externi_id)
                    .HasName("externi_id");

                entity.HasIndex(e => e.faktura_doklad)
                    .HasName("faktura_doklad");

                entity.HasIndex(e => e.faktura_id)
                    .HasName("faktura_id");

                entity.HasIndex(e => e.finish)
                    .HasName("finish");

                entity.HasIndex(e => e.operation_id)
                    .HasName("operation_id");

                entity.HasIndex(e => e.order_group_id)
                    .HasName("order_group_id");

                entity.HasIndex(e => e.order_id)
                    .HasName("order_id");

                entity.HasIndex(e => e.orderwork_id)
                    .HasName("orderwork_id");

                entity.HasIndex(e => e.poradi_operace)
                    .HasName("poradi_operace");

                entity.HasIndex(e => e.repair_type)
                    .HasName("repair_type");

                entity.HasIndex(e => e.serial_id)
                    .HasName("serial_id");

                entity.HasIndex(e => e.serial_id_str)
                    .HasName("serial_id_str");

                entity.HasIndex(e => e.start)
                    .HasName("start");

                entity.HasIndex(e => e.ts_created)
                    .HasName("ts_created");

                entity.HasIndex(e => e.ts_lastChange)
                    .HasName("ts_lastChange");

                entity.HasIndex(e => e.typ_ukon_mzdy)
                    .HasName("typ_ukon_mzdy");

                entity.HasIndex(e => e.worker_id)
                    .HasName("worker_id");

                entity.HasIndex(e => e.worker_id2)
                    .HasName("worker_id2");

                entity.HasIndex(e => new { e.order_id, e.operation_id })
                    .HasName("slozenyIndex1");

                entity.HasIndex(e => new { e.order_id, e.start })
                    .HasName("slozenyIndexOperIdStart");

                entity.HasIndex(e => new { e.worker_id, e.worker_id2 })
                    .HasName("worker_id12");

                entity.HasIndex(e => new { e.order_id, e.finish, e.id, e.start })
                    .HasName("slozenyIndex3");

                entity.Property(e => e.added_price)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.calculated)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.calculated_kalendar)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.calculated_machine)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.calculated_orderwork)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cena_MJ)
                    .HasColumnType("decimal(15,4)")
                    .HasDefaultValueSql("'0.0000'");

                entity.Property(e => e.cena_cnc)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.cena_operation)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.cena_stroj)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.cena_worker)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.cena_worker2)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.ceny_added)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.dodaci_list_polozka_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.exportovano)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.externi_id).HasColumnType("varchar(100)");

                entity.Property(e => e.faktura_doklad).HasColumnType("varchar(150)");

                entity.Property(e => e.faktura_id).HasColumnType("int(15)");

                entity.Property(e => e.finish)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.hnizdo).HasColumnType("int(11)");

                entity.Property(e => e.kusy_zapocteno)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.locked)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.mnoz)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.naklady)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.naklady_operation)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.naklady_order)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.naklady_vstup)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.naklady_worker)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.note).HasColumnType("text");

                entity.Property(e => e.operation_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.order_group_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.order_id)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.orderwork_id).HasColumnType("int(11)");

                entity.Property(e => e.photo_count)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.poradi_operace).HasColumnType("int(4)");

                entity.Property(e => e.prepocitano)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.priorita)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.repair_type)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.sarze)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.serial_id).HasDefaultValueSql("'0'");

                entity.Property(e => e.serial_id_str).HasColumnType("varchar(50)");

                entity.Property(e => e.start)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.terminal_ip)
                    .IsRequired()
                    .HasColumnType("varchar(64)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.ts_created)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                entity.Property(e => e.ts_lastChange)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'")
                    .ValueGeneratedOnAddOrUpdate();

                entity.Property(e => e.typ_ukon_mzdy)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'-1'");

                entity.Property(e => e.typ_vypoctu)
                    .HasColumnType("int(2)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.ukon_mzda)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.ukonova_mzda)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.um_fond_odpis).HasColumnType("int(15)");

                entity.Property(e => e.um_fond_zbyva).HasColumnType("int(15)");

                entity.Property(e => e.um_uznano).HasColumnType("int(15)");

                entity.Property(e => e.um_uznano_datum).HasColumnType("datetime");

                entity.Property(e => e.um_uznano_user).HasColumnType("varchar(100)");

                entity.Property(e => e.user)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");

                entity.Property(e => e.volitelna1)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.volitelna2)
                    .HasColumnType("decimal(7,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.worker_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.worker_id2)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.zamceno)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.zamceno_cas)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.zamceno_id_user)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.zmetku)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");
            });

            modelBuilder.Entity<worker>(entity =>
            {
                entity.HasIndex(e => e.active)
                    .HasName("active");

                entity.HasIndex(e => e.bar_id)
                    .HasName("bar_id");

                entity.HasIndex(e => e.finish)
                    .HasName("finish");

                entity.HasIndex(e => e.gdpr_zbyva)
                    .HasName("gdpr_zbyva");

                entity.HasIndex(e => e.group_name)
                    .HasName("group_name");

                entity.HasIndex(e => e.id_misto_prace)
                    .HasName("id_misto_prace");

                entity.HasIndex(e => e.id_nadrizeny)
                    .HasName("id_nadrizeny");

                entity.HasIndex(e => e.id_pracovni_skupina)
                    .HasName("id_pracovni_skupina");

                entity.HasIndex(e => e.id_profese)
                    .HasName("id_profese");

                entity.HasIndex(e => e.id_ridici_struktura)
                    .HasName("id_ridici_struktura");

                entity.HasIndex(e => e.name)
                    .HasName("name");

                entity.HasIndex(e => e.pozice)
                    .HasName("pozice");

                entity.HasIndex(e => e.start)
                    .HasName("start");

                entity.HasIndex(e => e.ts_created)
                    .HasName("ts_created");

                entity.HasIndex(e => e.ts_lastChange)
                    .HasName("ts_lastChange");

                entity.Property(e => e.id).HasColumnType("int(11)");

                entity.Property(e => e.active)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.alias)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.bar_id)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.bezCasu)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.busyStart)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.card)
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.card_dmr)
                    .IsRequired()
                    .HasColumnType("varchar(64)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.cena_fakturace)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.cnc)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_end_operation_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_group)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_alarm)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_busy)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_feed)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_idle)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_konec)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_kontrola)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_nedefinovano)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_odevzdaniks)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_prihlaseni)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_servis)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_sing)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_udrzba)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_operation_waitkontrola)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_servis_datum)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'1899-12-30'");

                entity.Property(e => e.cnc_servis_interval)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.cnc_servis_interval_unit)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.cnc_start_operation_id)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.comment).HasColumnType("text");

                entity.Property(e => e.dostupne_smeny)
                    .IsRequired()
                    .HasColumnType("varchar(256)")
                    .HasDefaultValueSql("'ALL'");

                entity.Property(e => e.email)
                    .IsRequired()
                    .HasColumnType("varchar(150)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.finish)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'0000-00-00'");

                entity.Property(e => e.gdpr_anonymizovano)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.gdpr_zbyva)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.group_name)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.id_misto_prace)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.id_nadrizeny)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.id_pracovni_skupina)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.id_profese)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.id_ridici_struktura)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.koef_skut_nakl)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'1.000'");

                entity.Property(e => e.koef_ukol_mzdy)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'1.000'");

                entity.Property(e => e.koef_ukol_mzdy2)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'1.000'");

                entity.Property(e => e.koef_ukol_mzdy2_type)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.koef_ukol_mzdy_type)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.lastCycle)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("'0000-00-00 00:00:00'");

                entity.Property(e => e.misto_prace)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.name)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.pouzeDochazka)
                    .HasColumnType("int(1)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.pozice)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.price_mzda)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'0.000'");

                entity.Property(e => e.price_prescas)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.price_sat)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.price_sat_koef)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'1.000'");

                entity.Property(e => e.price_sun)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");

                entity.Property(e => e.price_sun_koef)
                    .HasColumnType("decimal(15,3)")
                    .HasDefaultValueSql("'1.000'");

                entity.Property(e => e.prihlaseni)
                    .IsRequired()
                    .HasColumnType("enum('bar_id','user_pin')")
                    .HasDefaultValueSql("'bar_id'");

                entity.Property(e => e.priorita)
                    .HasColumnType("int(11)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.profese)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.smena)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.start)
                    .HasColumnType("date")
                    .HasDefaultValueSql("'0000-00-00'");

                entity.Property(e => e.stavCnc)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.telefon)
                    .IsRequired()
                    .HasColumnType("varchar(150)")
                    .HasDefaultValueSql("''");

                entity.Property(e => e.ts_created)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'");

                entity.Property(e => e.ts_lastChange)
                    .HasColumnType("timestamp")
                    .HasDefaultValueSql("'CURRENT_TIMESTAMP'")
                    .ValueGeneratedOnAddOrUpdate();

                entity.Property(e => e.type)
                    .HasColumnType("int(5)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.use_cena_fakturace)
                    .HasColumnType("int(3)")
                    .HasDefaultValueSql("'0'");

                entity.Property(e => e.user)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasDefaultValueSql("'SYSTEM'");

                entity.Property(e => e.user_pin).HasDefaultValueSql("'0'");

                entity.Property(e => e.workerprice)
                    .HasColumnType("decimal(15,2)")
                    .HasDefaultValueSql("'0.00'");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}