// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCRUD1
{
    public partial class operation
    {
        public ulong id { get; set; }
        public string bar_id { get; set; }
        public string name { get; set; }
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string note { get; set; }
        public string machine_name { get; set; }
        public int id_employee { get; set; }
        public int unit { get; set; }
        public decimal unitcount { get; set; }
        public decimal unit_price { get; set; }
        public string user { get; set; }
        public int open_door { get; set; }
        public int orderstav_id { get; set; }
        public decimal ukolova_mzda { get; set; }
        public int auto_writte { get; set; }
        public int cnc_id { get; set; }
        public decimal cena_mzdove_polozky { get; set; }
        public int maxmin_za_den { get; set; }
        public int planovano_min { get; set; }
        public int resource_id { get; set; }
        public int take_photo { get; set; }
        public int? operace_predchazejici_id { get; set; }
        public int? operace_predchazejici_cas { get; set; }
        public int? operace_predchazejici_fix { get; set; }
        public string externi_id { get; set; }
        public int priprava { get; set; }
        public int pripravaCas { get; set; }
        public int pripravaInterval { get; set; }
        public decimal cena_faktura { get; set; }
        public decimal cena_rezie { get; set; }
        public decimal koeficient_mzdy { get; set; }
        public int sklad_skupina_id { get; set; }
        public decimal cena_mj_odmeny { get; set; }
        public decimal cena_mj_operace { get; set; }
        public int is_cnc { get; set; }
        public DateTime ts_lastChange { get; set; }
        public DateTime ts_created { get; set; }
        public int is_dochazka { get; set; }
        public string userCode { get; set; }
    }
}