// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCRUD1
{
    public partial class order_stav
    {
        public int id { get; set; }
        public string name { get; set; }
        public string user { get; set; }
        public string group_name { get; set; }
        public int poradi { get; set; }
        public ulong change_operation_id { get; set; }
        public string cislo { get; set; }
        public int pocitat_plan { get; set; }
        public int in_print { get; set; }
        public int prepocitavat { get; set; }
        public int blokace_mat { get; set; }
        public int barevne_oznaceni { get; set; }
        public int barva { get; set; }
        public int stav_vyroba { get; set; }
        public int FinalStatus { get; set; }
    }
}