// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorCRUD1
{
    public partial class worker
    {
        public int id { get; set; }
        public string name { get; set; }
        public string bar_id { get; set; }
        public string comment { get; set; }
        public DateTime start { get; set; }
        public string active { get; set; }
        public DateTime finish { get; set; }
        public string user { get; set; }
        public decimal workerprice { get; set; }
        public decimal price_sat { get; set; }
        public decimal price_sun { get; set; }
        public int type { get; set; }
        public int cnc { get; set; }
        public string card { get; set; }
        public string group_name { get; set; }
        public string profese { get; set; }
        public string misto_prace { get; set; }
        public string smena { get; set; }
        public string dostupne_smeny { get; set; }
        public int cnc_start_operation_id { get; set; }
        public int cnc_end_operation_id { get; set; }
        public int cnc_operation_prihlaseni { get; set; }
        public int cnc_operation_kontrola { get; set; }
        public int cnc_operation_servis { get; set; }
        public int cnc_operation_odevzdaniks { get; set; }
        public int cnc_operation_idle { get; set; }
        public int cnc_operation_alarm { get; set; }
        public int cnc_operation_sing { get; set; }
        public int cnc_operation_feed { get; set; }
        public int cnc_operation_busy { get; set; }
        public string card_dmr { get; set; }
        public int cnc_operation_udrzba { get; set; }
        public string stavCnc { get; set; }
        public DateTime busyStart { get; set; }
        public DateTime lastCycle { get; set; }
        public int cnc_operation_konec { get; set; }
        public int cnc_operation_nedefinovano { get; set; }
        public int cnc_operation_waitkontrola { get; set; }
        public string alias { get; set; }
        public int priorita { get; set; }
        public decimal cena_fakturace { get; set; }
        public int use_cena_fakturace { get; set; }
        public ulong user_pin { get; set; }
        public string prihlaseni { get; set; }
        public int cnc_group { get; set; }
        public decimal price_prescas { get; set; }
        public string pozice { get; set; }
        public int id_nadrizeny { get; set; }
        public int id_pracovni_skupina { get; set; }
        public int id_ridici_struktura { get; set; }
        public int id_profese { get; set; }
        public int id_misto_prace { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public decimal price_mzda { get; set; }
        public DateTime cnc_servis_datum { get; set; }
        public decimal cnc_servis_interval { get; set; }
        public int cnc_servis_interval_unit { get; set; }
        public decimal koef_skut_nakl { get; set; }
        public int gdpr_zbyva { get; set; }
        public int gdpr_anonymizovano { get; set; }
        public int pouzeDochazka { get; set; }
        public int bezCasu { get; set; }
        public decimal price_sat_koef { get; set; }
        public decimal price_sun_koef { get; set; }
        public decimal koef_ukol_mzdy { get; set; }
        public DateTime ts_lastChange { get; set; }
        public DateTime ts_created { get; set; }
        public int koef_ukol_mzdy_type { get; set; }
        public decimal koef_ukol_mzdy2 { get; set; }
        public int koef_ukol_mzdy2_type { get; set; }
    }
}